version: "3"

services:
  api:
    container_name: sponsvisa-backend
    image: ghcr.io/nima-ca/sponsvisa-api:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - prod.env

  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - prod.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5000:80"
    env_file:
      - prod.env
    volumes:
      - /var/lib/pgadmin
    restart: unless-stopped
